---
name: "Feature"
about: "Template for new features"
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

---

- type: markdown
  attributes:
    value: |
      Please ensure you have read the Code of Conduct before submitting your new feature.

- type: checkboxes
  attributes:
    label: Conduct
    description: You need to have Read and Accepted the Code of Conduct
    options:
      - label: Did you Read the Code of Conduct?
        required: true
      - label: Will you follow the Code of Conduct?
        required: true

- type: input
  id: title
  attributes:
    label: What is the new feature?
    description: Provide a brief description of the new feature you are adding.
    placeholder: Adding a new user profile page
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      # Thank you for your Contribution
