import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from ">ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import { AnimatePresence } from "framer-motion";
import { Toolbar } from ">comp/Toolbar";
import { DefaultText } from ">util/className";
import { cn } from ">util/twm";

export const metadata: Metadata = {
  title: "Hamburg Hack A Ton!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <SpeedInsights />
        <Analytics />
        <link
          rel="stylesheet"
          href="https://use.typekit.net/nib2aic.css"
        ></link>
      </head>
      <body
        className={cn(
          DefaultText,
          "antialiased bg-background duration-200 text-foreground"
        )}
      >
        <AnimatePresence>{children}</AnimatePresence>
        <Toaster />
      </body>
      <Toolbar />
    </html>
  );
}
