import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Hamburg Hack A Ton!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-background text-primary-foreground`}
      >
        <SpeedInsights />
        <Analytics />
        <link rel="stylesheet" href="https://use.typekit.net/nib2aic.css"></link>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
